language: node_js
node_js:
  - 10.16.1
before_install:
  - npm install -g firebase-tools
install:
  - yarn install
  - (cd functions && yarn install)
script: firebase emulators:exec --only firestore 'yarn test'
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT
